"""add_inspector_reviews_table

Revision ID: 10f51a62d3a8
Revises: cd34b5de42c0
Create Date: 2026-09-29 01:58:51.224235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10f51a62d3a8'
down_revision: Union[str, Sequence[str], None] = 'cd34b5de42c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    screening_verdict_enum = postgresql.ENUM('PASS', 'REVIEW', 'REJECT', name='screening_verdict_enum', create_type=False)
    op.create_table('inspector_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.String(length=64), nullable=False),
    sa.Column('original_verdict', screening_verdict_enum, nullable=False),
    sa.Column('disposition', sa.Enum('ACCEPTED', 'QUARANTINED', 'RE_TEST', name='review_disposition_enum'), nullable=False),
    sa.Column('inspector_notes', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspector_reviews_component_id'), 'inspector_reviews', ['component_id'], unique=False)
    op.create_index(op.f('ix_inspector_reviews_disposition'), 'inspector_reviews', ['disposition'], unique=False)
    op.create_index(op.f('ix_inspector_reviews_inspector_id'), 'inspector_reviews', ['inspector_id'], unique=False)
    op.create_index('ix_reviews_component_date', 'inspector_reviews', ['component_id', 'reviewed_at'], unique=False)
    op.create_index('ix_reviews_inspector_disposition', 'inspector_reviews', ['inspector_id', 'disposition'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_inspector_disposition', table_name='inspector_reviews')
    op.drop_index('ix_reviews_component_date', table_name='inspector_reviews')
    op.drop_index(op.f('ix_inspector_reviews_inspector_id'), table_name='inspector_reviews')
    op.drop_index(op.f('ix_inspector_reviews_disposition'), table_name='inspector_reviews')
    op.drop_index(op.f('ix_inspector_reviews_component_id'), table_name='inspector_reviews')
    op.drop_table('inspector_reviews')
    sa.Enum(name='review_disposition_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
