"""initial_burn_in_schema

Revision ID: 9635d36eca2d
Revises: 
Create Date: 2026-09-29 01:31:42.153242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9635d36eca2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=64), nullable=False),
    sa.Column('wafer_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('INGESTED', 'SCREENED', 'REVIEW_PENDING', name='lot_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_lot_number'), 'lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_index(op.f('ix_lots_wafer_id'), 'lots', ['wafer_id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('ground_truth_label', sa.Enum('NORMAL', 'LEVEL_OUTLIER', 'STEEP_DRIFT', 'LATE_DRIFT', 'SUBTLE_MULTIVARIATE', name='ground_truth_label_enum'), nullable=False),
    sa.Column('ground_truth_flag', sa.Boolean(), nullable=False),
    sa.Column('is_datasheet_breached', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'serial_number', name='uq_component_lot_serial')
    )
    op.create_index(op.f('ix_components_ground_truth_flag'), 'components', ['ground_truth_flag'], unique=False)
    op.create_index(op.f('ix_components_ground_truth_label'), 'components', ['ground_truth_label'], unique=False)
    op.create_index(op.f('ix_components_is_datasheet_breached'), 'components', ['is_datasheet_breached'], unique=False)
    op.create_index(op.f('ix_components_lot_id'), 'components', ['lot_id'], unique=False)
    op.create_index('ix_components_lot_id_flag', 'components', ['lot_id', 'ground_truth_flag'], unique=False)
    op.create_index(op.f('ix_components_serial_number'), 'components', ['serial_number'], unique=False)
    op.create_table('burn_in_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('leakage_current_ua', sa.Float(), nullable=False),
    sa.Column('iddq_ma', sa.Float(), nullable=False),
    sa.Column('propagation_delay_ns', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_hours >= 0', name='chk_interval_hours_non_negative'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'interval_hours', name='uq_reading_component_interval')
    )
    op.create_index(op.f('ix_burn_in_readings_component_id'), 'burn_in_readings', ['component_id'], unique=False)
    op.create_index('ix_readings_component_interval', 'burn_in_readings', ['component_id', 'interval_hours'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_readings_component_interval', table_name='burn_in_readings')
    op.drop_index(op.f('ix_burn_in_readings_component_id'), table_name='burn_in_readings')
    op.drop_table('burn_in_readings')
    op.drop_index(op.f('ix_components_serial_number'), table_name='components')
    op.drop_index('ix_components_lot_id_flag', table_name='components')
    op.drop_index(op.f('ix_components_lot_id'), table_name='components')
    op.drop_index(op.f('ix_components_is_datasheet_breached'), table_name='components')
    op.drop_index(op.f('ix_components_ground_truth_label'), table_name='components')
    op.drop_index(op.f('ix_components_ground_truth_flag'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_lots_wafer_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index(op.f('ix_lots_lot_number'), table_name='lots')
    op.drop_table('lots')
    # ### end Alembic commands ###
